
print '/* generated by pgdir.pl - do not edit */
#include <stdint.h>
#include "mmu.h"

__attribute__((__aligned__(PGSIZE)))
uint64_t entry_pmd[512] = {
';

for (my $i = 0; $i < 512; $i++) {
  my $pa = $i*2*1024*1024;
  printf("  0x%X | ", $pa);
  if ($pa >= 0x3F000000) {
    print "MMU_DEVICE_FLAGS";
  }
  else {
    print "MMU_FLAGS";
  }

  if ($i != 511) {
    print ",\n";
  }
}

print '
};

__attribute__((__aligned__(PGSIZE)))
uint64_t entry_pud[512] = { (uint64_t)entry_pmd + MM_TYPE_PAGE };

__attribute__((__aligned__(PGSIZE)))
uint64_t entry_pgd[512] = { (uint64_t)entry_pud + MM_TYPE_PAGE };
';
